name: publish
on: [push]
jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CircleCI
        id: trigger-circle
        uses: circleci/trigger_circleci_pipeline@v1.0
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the hello-docker Docker image
        run: |
          docker build . --tag ghcr.io/thomasmatecki/can-it-cat:latest
          docker push ghcr.io/thomasmatecki/can-it-cat:latest
